version: '3'
services:
  cron-awesome-books:
    build: './docker/php-fpm'
    volumes:
      - './:/app'
    networks:
      - cron-awesome
networks:
  cron-awesome:
    name: awesome_network
    external: true